services:
  windows:
    image: dockurr/windows
    environment:
      DISK_SIZE: "64G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_TYPE: "ide"
      ARGUMENTS: "-drive file=/driver.iso,media=cdrom"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /mnt:/storage
      - /isos/a.iso:/custom.iso
      - /isos/driver.iso:/driver.iso
    stop_grace_period: 2m
